import { expect, test } from '@playwright/test'

test('retains independent card and asset zoom settings and switches the preview mode', async ({ page }) => {
  await page.goto('/cards?demo=1')
  const canvas = page.getByLabel('カード編集キャンバス')
  await expect(canvas).toBeVisible()
  const image = await canvas.screenshot()
  await page.getByRole('combobox', { name: '表示倍率', exact: true }).selectOption('100')
  await expect.poll(() => canvas.evaluate((element: HTMLCanvasElement) => element.getBoundingClientRect().width / element.width)).toBe(1)
  await page.getByRole('button', { name: '元画像', exact: true }).click()
  await expect(page.getByRole('button', { name: '元画像', exact: true })).toHaveClass(/selected/)
  await page.getByRole('button', { name: 'アセット編集', exact: true }).click()
  await page.locator('.asset-editor-layout input[type=file]').setInputFiles({ name: 'source.png', mimeType: 'image/png', buffer: image })
  const source = page.getByLabel('アセット切り出し元画像')
  await expect(source).toBeVisible()
  await page.getByRole('combobox', { name: '表示倍率', exact: true }).selectOption('75')
  await expect.poll(() => source.evaluate((element: HTMLCanvasElement) => element.getBoundingClientRect().width / element.width)).toBe(0.75)
  await page.getByRole('button', { name: 'カード', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '表示倍率', exact: true })).toHaveValue('100')
  await expect(page.getByRole('button', { name: '元画像', exact: true })).toHaveClass(/selected/)
  await page.getByRole('button', { name: '編集結果', exact: true }).click()
  await expect(page.getByRole('button', { name: '編集結果', exact: true })).toHaveClass(/selected/)
  await page.getByRole('button', { name: 'アセット編集', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '表示倍率', exact: true })).toHaveValue('75')
})

test('inspector tools control Canvas strokes, undo, and mutually exclusive editing modes', async ({ page }) => {
  await page.goto('/cards?demo=1')
  const canvas = page.getByLabel('カード編集キャンバス')
  await expect(canvas).toBeVisible()
  const bounds = await canvas.boundingBox()
  if (!bounds)
    throw new Error('Canvas has no layout bounds')
  await page.mouse.move(bounds.x + 30, bounds.y + 30)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 220, bounds.y + 150, { steps: 10 })
  await page.mouse.up()
  await page.locator('#inspector-tab-region').click()
  await page.getByRole('combobox', { name: '背景処理', exact: true }).selectOption('manual')
  const size = page.getByLabel('ブラシサイズ', { exact: true })
  await size.focus()
  await size.press('End')
  await expect(size).toHaveValue('80')
  await page.getByRole('button', { name: 'マスクをブラシで編集', exact: true }).click()
  await expect(page.getByRole('button', { name: 'マスク編集を終了', exact: true })).toBeVisible()
  const pixels = () => canvas.evaluate((element: HTMLCanvasElement) => element.toDataURL())
  const before = await pixels()
  await page.mouse.move(bounds.x + 80, bounds.y + 80)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 160, bounds.y + 80, { steps: 10 })
  await page.mouse.up()
  await page.mouse.move(10, 10)
  await expect.poll(pixels).not.toBe(before)
  const painted = await pixels()
  await page.getByRole('combobox', { name: 'ブラシ', exact: true }).selectOption('erase')
  await page.mouse.move(bounds.x + 80, bounds.y + 80)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 160, bounds.y + 80, { steps: 10 })
  await page.mouse.up()
  await page.mouse.move(10, 10)
  await expect.poll(pixels).not.toBe(painted)
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await expect.poll(pixels).toBe(painted)
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await expect.poll(pixels).toBe(before)
  await page.getByRole('button', { name: '保護領域を追加', exact: true }).click()
  await expect(page.getByRole('button', { name: 'マスクをブラシで編集', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '画像上をドラッグ', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'マスクをブラシで編集', exact: true }).click()
  await expect(page.getByRole('button', { name: '保護領域を追加', exact: true })).toBeVisible()
  await expect(size).toHaveValue('80')
})

test('translation changes Canvas pixels and region deletion can be cancelled and undone', async ({ page }) => {
  await page.goto('/cards?demo=1')
  const canvas = page.getByLabel('カード編集キャンバス')
  await expect(canvas).toBeVisible()
  const bounds = await canvas.boundingBox()
  if (!bounds)
    throw new Error('Canvas has no layout bounds')
  await page.mouse.move(bounds.x + 30, bounds.y + 30)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 220, bounds.y + 100, { steps: 10 })
  await page.mouse.up()
  await page.locator('#inspector-tab-list').click()
  const regions = page.locator('.region-list-item')
  await expect(regions).toHaveCount(1)
  const count = await regions.count()
  expect(count).toBeGreaterThan(0)
  await page.locator('.region-list-select').first().click()
  await page.locator('#inspector-tab-text').click()
  const translation = page.getByLabel('日本語訳', { exact: true })
  await expect(translation).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  const pixels = () => canvas.evaluate((element: HTMLCanvasElement) => element.toDataURL())
  const before = await pixels()
  await translation.fill('Playwright 描画確認')
  await translation.blur()
  await expect.poll(pixels).not.toBe(before)
  await page.locator('#inspector-tab-list').click()
  await expect(page.locator('.region-list-select').first()).toContainText('Playwright 描画確認')
  await page.locator('.region-list-remove').first().click()
  const dialog = page.getByRole('alertdialog')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'キャンセル' }).press('Escape')
  await expect(dialog).toBeHidden()
  await expect(regions).toHaveCount(count)
  await page.locator('.region-list-remove').first().click()
  await dialog.locator('.confirmation-danger').click()
  await expect(regions).toHaveCount(count - 1)
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await expect(regions).toHaveCount(count)
  await expect(page.locator('.region-list-select').first()).toContainText('Playwright 描画確認')
})

test('demo renders a card and supports inspector keyboard navigation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/cards?demo=1')
  const canvas = page.getByLabel('カード編集キャンバス')
  await expect(canvas).toBeVisible()
  await expect.poll(() => canvas.evaluate((element: HTMLCanvasElement) => element.width)).toBeGreaterThan(0)
  await page.locator('#inspector-tab-list').click()
  await page.locator('#inspector-tab-list').press('End')
  await expect(page.locator('#inspector-tab-print')).toBeFocused()
  await expect(page.locator('#inspector-tab-print')).toHaveAttribute('aria-selected', 'true')
  await page.locator('#inspector-tab-print').press('Home')
  await expect(page.locator('#inspector-tab-list')).toBeFocused()
  await expect(canvas).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('card-editor.png') })
  expect(errors).toEqual([])
})

test('diagnostics opens from tools and closes with Escape', async ({ page }) => {
  await page.goto('/cards?demo=1')
  await expect(page.getByLabel('カード編集キャンバス')).toBeVisible()
  await page.getByText('ツール', { exact: true }).click()
  await page.getByText(/診断ログ/).click()
  const dialog = page.getByRole('dialog', { name: /診断ログ/ })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '閉じる', exact: true }).focus()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
})
