import { expect, test } from '@playwright/test'

test('shows original-resolution demo images in detected region previews', async ({ page }, testInfo) => {
  await page.goto('/cards?demo=1')
  await page.locator('.card-list-panel').getByRole('button', { name: '領域検出', exact: true }).click()
  const workspace = page.getByRole('region', { name: '領域検出・OCR', exact: true })
  await workspace.getByRole('button', { name: '5枚の領域を検出', exact: true }).click()
  const preview = workspace.locator('.candidate-card .region-source-preview image').first()
  await expect(preview).toHaveAttribute('href', /^blob:/)
  const size = await preview.evaluate(async (element) => {
    const image = new Image()
    image.src = element.getAttribute('href')!
    await image.decode()
    return { width: image.naturalWidth, height: image.naturalHeight }
  })
  expect(size).toEqual({ width: 744, height: 1039 })
  for (let index = 0; index < 5; index++) {
    const card = workspace.locator('.candidate-card').nth(index)
    await card.scrollIntoViewIfNeeded()
    await expect(card.locator('.region-source-preview image').first()).toHaveAttribute('href', /^blob:/)
    await card.screenshot({ path: testInfo.outputPath(`original-region-previews-${index + 1}.png`) })
  }
  await page.setViewportSize({ width: 600, height: 900 })
  expect(await workspace.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('explains zero new candidates after demo regions are added and continues to translation', async ({ page }, testInfo) => {
  await page.goto('/cards?demo=1')
  await page.locator('.card-list-panel').getByRole('button', { name: '領域検出', exact: true }).click()
  const workspace = page.getByRole('region', { name: '領域検出・OCR', exact: true })
  await workspace.getByRole('button', { name: '5枚の領域を検出', exact: true }).click()
  await expect(workspace.locator('.candidate-choice')).toHaveCount(20)
  await expect(workspace).toContainText('実OCRは実行していません')
  await workspace.locator('.candidate-choice input').first().check()
  await workspace.getByRole('button', { name: '選択した候補を追加（1件）', exact: true }).click()
  await expect(workspace.locator('.existing-region')).toHaveCount(1)
  await expect(workspace.locator('.candidate-choice')).toHaveCount(19)
  await expect(workspace.getByRole('button', { name: '翻訳へ進む', exact: true })).toBeEnabled()
  await workspace.locator('.existing-region').getByRole('button', { name: 'この領域を編集', exact: true }).click()
  await page.getByRole('tab', { name: '翻訳', exact: true }).click()
  await page.getByLabel('元テキスト', { exact: true }).fill('Edited source')
  await page.getByRole('button', { name: 'OCR結果に戻る', exact: true }).click()
  await expect(workspace.locator('.existing-region .candidate-text')).toHaveText('Edited source')
  await expect(workspace.locator('.candidate-choice input:checked')).toHaveCount(0)
  await workspace.getByRole('button', { name: '表示中の候補をすべて選択', exact: true }).click()
  await workspace.getByRole('button', { name: '選択した候補を追加（19件）', exact: true }).click()
  await expect(workspace.locator('.existing-region')).toHaveCount(20)
  await expect(workspace.getByRole('button', { name: '翻訳へ進む', exact: true })).toBeEnabled()
  const lastRegion = workspace.locator('.candidate-card').last().locator('.existing-region').last()
  await lastRegion.getByRole('button', { name: 'この領域を編集', exact: true }).scrollIntoViewIfNeeded()
  const scrollTop = await page.locator('.batch-workspace').evaluate(element => element.scrollTop)
  await lastRegion.getByRole('button', { name: 'この領域を編集', exact: true }).click()
  await page.getByRole('button', { name: 'OCR結果に戻る', exact: true }).click()
  // 原画像の遅延表示に伴う数pxの丸め差は許容し、閲覧位置のリセットを検出する。
  await expect.poll(async () => Math.abs(await page.locator('.batch-workspace').evaluate(element => element.scrollTop) - scrollTop)).toBeLessThanOrEqual(4)
  await workspace.getByRole('button', { name: '対象選択に戻る', exact: true }).click()
  await workspace.getByRole('button', { name: '5枚の領域を検出', exact: true }).click()
  await expect(workspace.locator('.existing-region')).toHaveCount(20)
  await expect(workspace.locator('.candidate-choice')).toHaveCount(0)
  await expect(page.locator('.card-ocr-state')).toHaveText(Array.from<string>({ length: 5 }).fill('領域 4件・追加候補なし'))
  await workspace.locator('.candidate-card').first().scrollIntoViewIfNeeded()
  await expect(workspace.locator('.existing-region .region-source-preview image').first()).toHaveAttribute('href', /^blob:/)
  await expect(page.locator('.notice')).toBeHidden({ timeout: 10000 })
  await page.screenshot({ path: testInfo.outputPath('added-regions-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await workspace.locator('.existing-region').first().scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(workspace.locator('.existing-region .region-source-preview image').first()).toHaveAttribute('href', /^blob:/)
  await page.screenshot({ path: testInfo.outputPath('added-regions-narrow.png') })
  await workspace.getByRole('button', { name: '翻訳へ進む', exact: true }).click()
  await expect(workspace).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'まとめて翻訳', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.translation-review')).toBeVisible()
})

test('lists all selected demo cards when detection opens and keeps the list after browsing a card', async ({ page }, testInfo) => {
  await page.goto('/cards?demo=1')
  await page.locator('.card-list-panel').getByRole('button', { name: '領域検出', exact: true }).click()
  const workspace = page.getByRole('region', { name: '領域検出・OCR', exact: true })
  const previews = workspace.locator('.batch-card-preview')
  await expect(previews).toHaveCount(5)
  await expect(previews.locator('strong')).toHaveText(['01-grove.png', '02-cloud.png', '03-compass.png', '04-orchard.png', '05-bridge.png'])
  await page.locator('.card-list-select').nth(1).click()
  await expect(previews).toHaveCount(5)
  await expect(workspace.getByRole('button', { name: '対象カードをすべて表示', exact: true })).toHaveCount(0)
  await page.getByLabel('02-cloud.pngを処理対象にする', { exact: true }).uncheck()
  await expect(previews).toHaveCount(4)
  await expect(previews.locator('strong')).toHaveText(['01-grove.png', '03-compass.png', '04-orchard.png', '05-bridge.png'])
  await expect(workspace.getByRole('button', { name: '4枚の領域を検出', exact: true })).toBeEnabled()
  await page.getByRole('combobox', { name: 'カードの選択条件' }).selectOption('none')
  await expect(previews).toHaveCount(0)
  await expect(workspace).toContainText('処理するカードを選んでください')
  await page.getByRole('combobox', { name: 'カードの選択条件' }).selectOption('all')
  await expect(previews).toHaveCount(5)
  await workspace.screenshot({ path: testInfo.outputPath('all-target-cards.png') })
})
