import { expect, test } from '@playwright/test'

test('registers an icon within the OCR workflow and retains it after undo', async ({ page }, testInfo) => {
  await page.goto('/cards?demo=1')
  const canvas = page.getByLabel('カード編集キャンバス')
  await expect(canvas).toBeVisible()
  const bounds = await canvas.boundingBox()
  if (!bounds)
    throw new Error('Canvas has no layout bounds')
  await page.mouse.move(bounds.x + 30, bounds.y + 30)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 220, bounds.y + 150, { steps: 10 })
  await page.mouse.up()
  await page.getByRole('button', { name: /元画像のアイコンを指定/ }).click()
  const dialog = page.getByRole('dialog', { name: '元画像のアイコンを指定・登録' })
  const svg = dialog.getByRole('img', { name: '元画像のアイコン指定範囲', exact: true })
  const rect = await svg.boundingBox()
  if (!rect)
    throw new Error('SVG has no layout bounds')
  await page.mouse.move(rect.x + rect.width * 0.4, rect.y + rect.height * 0.4)
  await page.mouse.down()
  await page.mouse.move(rect.x + rect.width * 0.5, rect.y + rect.height * 0.6, { steps: 10 })
  await page.mouse.up()
  await expect(dialog.getByRole('button', { name: '候補1を確認' })).toBeVisible()
  await dialog.getByRole('button', { name: 'この範囲から新規登録' }).click()
  await dialog.getByLabel('アイコン名', { exact: true }).fill('ocr_test_icon')
  await expect(dialog.getByLabel('背景透明化プレビュー')).toBeVisible()
  await dialog.getByRole('button', { name: 'アイコンを確定', exact: true }).click()
  await expect(dialog.getByLabel('アイコン1のアイコン')).not.toHaveValue('')
  await dialog.screenshot({ path: testInfo.outputPath('source-icons.png') })
  await dialog.getByRole('button', { name: 'アイコン指定を反映', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: '元画像のアイコンを指定（1）' })).toBeVisible()
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await expect(page.getByRole('button', { name: '元画像のアイコンを指定（0）' })).toBeVisible()
  await page.getByRole('button', { name: /元画像のアイコンを指定/ }).click()
  await expect(page.getByLabel('割り当てる登録済みアイコン').locator('option', { hasText: 'ocr_test_icon' })).toHaveCount(1)
})
